### ISSUE TITLE
Data

### ISSUE THREAD

**Issue by marcown** [dennisbappert/pytorch-licenseplate-segmentation#1]
Hey,

thanks for the nice repo. Can you provide the Dataset you trained the model on?

Thanks

**Comment by dbpprt** [comment]
I handcrafted the dataset using google image search and a couple of youtube videos. I finally used around 200 images in my training set however I can't share the dataset publicly due to possible copyright issues.

**Comment by ArunJoseph19** [comment]
Anna pls
